# log_config.yaml


log:
  FLAG: 'FILE' #{DB, FILE}
  FILE_CONFIG:
    name: 'log_file'
    filename: 'tst0821.log'
    directory: 'pipeline_file'
  DB_CONFIG:
    name: 'log_db'
    host: '128.2.209.147'
    port: 27017
    dbname: 'pipeline_db' 
    collection: 'vid_log' # update to video_name
  PROC_CONFIG:
    name: 'pipeline_proc'
    # URL: 'http://aladdin1.inf.cs.cmu.edu:83/api/swagger.json'
    URL: 'http://128.2.209.147:8888/api/swagger.json'


directory:
  DATA_DIR : &DATA_DIR '/home/wenhe/python/tst2017oct'
  # DATA_DIR : &DATA_DIR '/Users/allenlwh/Dropbox/Docker/pipline/data/'
  VIDEO_DIR : &VIDEO_DIR '/tmp/test_video'
  PREPROCESS_DIR : &PREPROCESS_DIR '/tmp/preprocess'
  PERSON_DETECT_DIR : &PERSON_DETECT_DIR '/tmp/persondetect'
  TRACK_DIR : &TRACK_DIR '/tmp/tracking'
  C3D_DIR : &C3D_DIR '/tmp/c3d'
  VLAD_DIR : &VLAD_DIR '/tmp/vlad'
  SVM_DIR : &SVM_DIR '/tmp/svm'
  DB_DIR : &DB_DIR '/tmp/db'

# nvida_docker parameters
nvida_docker:
  NV_GPU : &NV_GPU [1,2]

parallel:
  WORKER_NUM: 3
  timewait: 3
  timeout: 30
  test: False

registry:
  'aladdin1.inf.cs.cmu.edu:5001'
  #  '128.2.209.147:5000'

pipeline:
  name: &PIPENAME 'pipeline_test'
  preprocess:
    - db
    - web
  sequence:
    - preprocess
    - persondetect
    - tracking
    - c3d
    - vlad
    - svm
  parallel: True
